spring:
    application:
        name: blazemeter
    security:
        username: blaze
        password: blaze
        role: ADMIN
    datasource:
        url: jdbc:mysql://mysql/BlazeDemo?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: toor
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
            jadira:
                usertype:
                    autoRegisterUserTypes: true
server:
    port: 16666

logging:
  file: logs/blaze-demo-api.log

info:
    build:
        artifact: blaze-demo-api
        name: BlazeDemoAPI
        description: Api for blaze-demo app
        version: 1.0